### PR TITLE
Issue #32: Ensuring all keywords are matched, not just the last one.

### PR DESCRIPTION
**Pull request by patricknelson**
All changes:

- Ensuring all keywords are matched, not just the last one. Using `AND` instead of `OR` method of filtering results.
- Ensuring consistent JSON-encoded return values. 
- Also ensuring ability to override hard-coded attribute defaults (e.g. placeholder).

### CODE REVIEW

**Comment by patricknelson** [comment]
Also @tractorcow I'd like to note that this repository's tags aren't up to date. Currently the latest tag is `3.4.0` which goes back to 2015. Is that intentional? When I installed this via `composer` it installed that version and not the latest version.

Just making sure!

**Comment by tractorcow** [comment]
Oh dear, I need to clean these tags up sorry.

**Comment by tractorcow** [comment]
I've fixed the master alias to 3.4, and added https://github.com/tractorcow/silverstripe-autocomplete/releases/tag/3.4.1

**Comment by tractorcow** [comment]
https://github.com/tractorcow/silverstripe-autocomplete/releases/tag/3.5.1

**Comment by tractorcow** [comment]
As noted in https://github.com/tractorcow/silverstripe-autocomplete/issues/36, it looks like using filter() instead of filterAny() introduced a new bug.

**Pull request merged**
